---
- name: Install unzip
  hosts: localhost
  connection: local

  tasks:
    - name: Debian/Ubuntu set up
      when: ansible_os_family == "Debian"
      become: yes
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: Install unzip
          apt:
            name: unzip
            state: present
